<div class="access-wrap">
				<div class="container">
					<nav id="access" role="navigation" class="app">
						<h3 class="assistive-text">Main menu</h3>
							<div class="menu-menu-container"><ul id="menu-menu" class="menu"><li id="menu-item-173" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-159 current_page_item menu-item-173"><a href="./index_files/index.html" class="menu-image-title-after menu-image-not-hovered">Home</a></li>
<li id="menu-item-122" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-122"><a href="http://www.publishing.visiomundi.net/about-us/" class="menu-image-title-after menu-image-not-hovered">About Us</a></li>
<li id="menu-item-309" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-309"><a href="http://www.publishing.visiomundi.net/executive-team/" class="menu-image-title-after menu-image-not-hovered">Executive Team</a></li>
<li id="menu-item-805" class="use-mega-menu four-cols menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-805 have-submenu have-sub-menu"><a href="http://www.publishing.visiomundi.net/#" class="menu-image-title-after menu-image-not-hovered">Publishing<span class="sub-ico"> +</span></a>
<ul class="sub-menu mega"><div class="mega-inner">
	<li id="menu-item-196" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-196 have-submenu mega-item"><a href="http://www.publishing.visiomundi.net/natural-sciences/" class="menu-image-title-after menu-image-not-hovered">Natural Sciences</a>
	<ul class="">
		<li id="menu-item-967" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-967"><a href="http://www.publishing.visiomundi.net/product-category/applied-sciences/agriculture/" class="menu-image-title-after menu-image-not-hovered">Agriculture</a></li>
		<li id="menu-item-570" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-570"><a href="http://www.publishing.visiomundi.net/product-category/natural-sciences/space-sciences/astrobiology/" class="menu-image-title-after menu-image-not-hovered">Astrobiology</a></li>
		<li id="menu-item-571" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-571"><a href="http://www.publishing.visiomundi.net/product-category/natural-sciences/space-sciences/astronomy/" class="menu-image-title-after menu-image-not-hovered">Astronomy</a></li>
		<li id="menu-item-572" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-572"><a href="http://www.publishing.visiomundi.net/product-category/natural-sciences/space-sciences/astrophysics/" class="menu-image-title-after menu-image-not-hovered">Astrophysics</a></li>
		<li id="menu-item-554" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-554"><a href="http://www.publishing.visiomundi.net/product-category/natural-sciences/biology/" class="menu-image-title-after menu-image-not-hovered">Biology</a></li>
		<li id="menu-item-555" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-555"><a href="http://www.publishing.visiomundi.net/product-category/natural-sciences/chemistry/" class="menu-image-title-after menu-image-not-hovered">Chemistry</a></li>
		<li id="menu-item-968" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-968"><a href="http://www.publishing.visiomundi.net/product-category/applied-sciences/computer-sciences/" class="menu-image-title-after menu-image-not-hovered">Computer sciences</a></li>
		<li id="menu-item-960" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-960"><a href="http://www.publishing.visiomundi.net/product-category/natural-sciences/earth-sciences/environmental-chemistry/" class="menu-image-title-after menu-image-not-hovered">Environmental chemistry</a></li>
		<li id="menu-item-961" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-961"><a href="http://www.publishing.visiomundi.net/product-category/natural-sciences/earth-sciences/environmental-science/" class="menu-image-title-after menu-image-not-hovered">Environmental science</a></li>
		<li id="menu-item-962" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-962"><a href="http://www.publishing.visiomundi.net/product-category/natural-sciences/earth-sciences/geology/" class="menu-image-title-after menu-image-not-hovered">Geology</a></li>
		<li id="menu-item-963" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-963"><a href="http://www.publishing.visiomundi.net/product-category/natural-sciences/earth-sciences/hydrogeology/" class="menu-image-title-after menu-image-not-hovered">Hydrogeology</a></li>
		<li id="menu-item-965" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-965"><a href="http://www.publishing.visiomundi.net/product-category/formal-sciences/logic/" class="menu-image-title-after menu-image-not-hovered">Logic</a></li>
		<li id="menu-item-966" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-966"><a href="http://www.publishing.visiomundi.net/product-category/formal-sciences/mathematics/" class="menu-image-title-after menu-image-not-hovered">Mathematics</a></li>
		<li id="menu-item-951" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-951"><a href="http://www.publishing.visiomundi.net/product-category/applied-sciences/medicine/" class="menu-image-title-after menu-image-not-hovered">Medicine</a></li>
		<li id="menu-item-964" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-964"><a href="http://www.publishing.visiomundi.net/product-category/natural-sciences/earth-sciences/meteorology/" class="menu-image-title-after menu-image-not-hovered">Meteorology</a></li>
		<li id="menu-item-952" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-952"><a href="http://www.publishing.visiomundi.net/product-category/natural-sciences/physics/" class="menu-image-title-after menu-image-not-hovered">Physics</a></li>
	</ul>
</li>
	<li id="menu-item-195" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-195 have-submenu mega-item"><a href="http://www.publishing.visiomundi.net/social-sciences/" class="menu-image-title-after menu-image-not-hovered">Social Sciences</a>
	<ul class="">
		<li id="menu-item-557" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-557"><a href="http://www.publishing.visiomundi.net/product-category/social-sciences/anthropology/" class="menu-image-title-after menu-image-not-hovered">Anthropology</a></li>
		<li id="menu-item-558" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-558"><a href="http://www.publishing.visiomundi.net/product-category/social-sciences/archeology/" class="menu-image-title-after menu-image-not-hovered">Archeology</a></li>
		<li id="menu-item-559" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-559"><a href="http://www.publishing.visiomundi.net/product-category/social-sciences/area-studies/" class="menu-image-title-after menu-image-not-hovered">Area studies</a></li>
		<li id="menu-item-560" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-560"><a href="http://www.publishing.visiomundi.net/product-category/social-sciences/communication-studies/" class="menu-image-title-after menu-image-not-hovered">Communication studies</a></li>
		<li id="menu-item-561" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-561"><a href="http://www.publishing.visiomundi.net/product-category/social-sciences/criminology/" class="menu-image-title-after menu-image-not-hovered">Criminology</a></li>
		<li id="menu-item-562" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-562"><a href="http://www.publishing.visiomundi.net/product-category/social-sciences/cultural-and-ethnic-studies/" class="menu-image-title-after menu-image-not-hovered">Cultural and ethnic studies</a></li>
		<li id="menu-item-566" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-566"><a href="http://www.publishing.visiomundi.net/product-category/social-sciences/gender-and-sexuality-studies/" class="menu-image-title-after menu-image-not-hovered">Gender and sexuality studies</a></li>
		<li id="menu-item-567" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-567"><a href="http://www.publishing.visiomundi.net/product-category/social-sciences/geography/" class="menu-image-title-after menu-image-not-hovered">Geography</a></li>
		<li id="menu-item-563" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-563"><a href="http://www.publishing.visiomundi.net/product-category/social-sciences/demography/" class="menu-image-title-after menu-image-not-hovered">Demography</a></li>
		<li id="menu-item-564" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-564"><a href="http://www.publishing.visiomundi.net/product-category/social-sciences/economics/" class="menu-image-title-after menu-image-not-hovered">Economics</a></li>
		<li id="menu-item-565" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-565"><a href="http://www.publishing.visiomundi.net/product-category/social-sciences/enviromental-studies/" class="menu-image-title-after menu-image-not-hovered">Enviromental studies</a></li>
		<li id="menu-item-568" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-568"><a href="http://www.publishing.visiomundi.net/product-category/social-sciences/information-science/" class="menu-image-title-after menu-image-not-hovered">Information science</a></li>
		<li id="menu-item-569" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-569"><a href="http://www.publishing.visiomundi.net/product-category/social-sciences/library-science/" class="menu-image-title-after menu-image-not-hovered">Library science</a></li>
		<li id="menu-item-550" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-550"><a href="http://www.publishing.visiomundi.net/product-category/social-sciences/pedagogy/" class="menu-image-title-after menu-image-not-hovered">Pedagogy</a></li>
		<li id="menu-item-551" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-551"><a href="http://www.publishing.visiomundi.net/product-category/social-sciences/political-science/" class="menu-image-title-after menu-image-not-hovered">Political science</a></li>
		<li id="menu-item-552" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-552"><a href="http://www.publishing.visiomundi.net/product-category/social-sciences/psychology/" class="menu-image-title-after menu-image-not-hovered">Psychology</a></li>
		<li id="menu-item-553" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-553"><a href="http://www.publishing.visiomundi.net/product-category/social-sciences/sociology/" class="menu-image-title-after menu-image-not-hovered">Sociology</a></li>
	</ul>
</li>
	<li id="menu-item-187" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-187 have-submenu mega-item"><a href="http://www.publishing.visiomundi.net/humanities/" class="menu-image-title-after menu-image-not-hovered">Humanities</a>
	<ul class="">
		<li id="menu-item-499" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-499"><a href="http://www.publishing.visiomundi.net/product-category/humanities/cinematology/" class="menu-image-title-after menu-image-not-hovered">Cinematology</a></li>
		<li id="menu-item-500" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-500"><a href="http://www.publishing.visiomundi.net/product-category/humanities/history/" class="menu-image-title-after menu-image-not-hovered">History</a></li>
		<li id="menu-item-501" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-501"><a href="http://www.publishing.visiomundi.net/product-category/humanities/law/" class="menu-image-title-after menu-image-not-hovered">Law</a></li>
		<li id="menu-item-502" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-502"><a href="http://www.publishing.visiomundi.net/product-category/humanities/linguistics/" class="menu-image-title-after menu-image-not-hovered">Linguistics</a></li>
		<li id="menu-item-503" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-503"><a href="http://www.publishing.visiomundi.net/product-category/humanities/musicology/" class="menu-image-title-after menu-image-not-hovered">Musicology</a></li>
		<li id="menu-item-950" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-950"><a href="http://www.publishing.visiomundi.net/product-category/humanities/philosophy/" class="menu-image-title-after menu-image-not-hovered">Philosophy</a></li>
		<li id="menu-item-947" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-947"><a href="http://www.publishing.visiomundi.net/product-category/humanities/theatrology/" class="menu-image-title-after menu-image-not-hovered">Theatrology</a></li>
		<li id="menu-item-949" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-949"><a href="http://www.publishing.visiomundi.net/product-category/humanities/theology/" class="menu-image-title-after menu-image-not-hovered">Theology</a></li>
	</ul>
</li>
	<li id="menu-item-183" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-183 have-submenu mega-item"><a href="http://www.publishing.visiomundi.net/arts/" class="menu-image-title-after menu-image-not-hovered">Arts and Literature</a>
	<ul class="">
		<li id="menu-item-491" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-491"><a href="http://www.publishing.visiomundi.net/product-category/arts/architecture/" class="menu-image-title-after menu-image-not-hovered">Architecture</a></li>
		<li id="menu-item-496" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-496"><a href="http://www.publishing.visiomundi.net/product-category/arts/dance/" class="menu-image-title-after menu-image-not-hovered">Dance</a></li>
		<li id="menu-item-492" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-492"><a href="http://www.publishing.visiomundi.net/product-category/arts/design/" class="menu-image-title-after menu-image-not-hovered">Design</a></li>
		<li id="menu-item-497" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-497"><a href="http://www.publishing.visiomundi.net/product-category/arts/film/" class="menu-image-title-after menu-image-not-hovered">Film</a></li>
		<li id="menu-item-490" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-490"><a href="http://www.publishing.visiomundi.net/product-category/arts/literature/" class="menu-image-title-after menu-image-not-hovered">Literature</a></li>
		<li id="menu-item-494" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-494"><a href="http://www.publishing.visiomundi.net/product-category/arts/music/" class="menu-image-title-after menu-image-not-hovered">Music</a></li>
		<li id="menu-item-493" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-493"><a href="http://www.publishing.visiomundi.net/product-category/arts/painting/" class="menu-image-title-after menu-image-not-hovered">Painting</a></li>
		<li id="menu-item-498" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-498"><a href="http://www.publishing.visiomundi.net/product-category/arts/photography/" class="menu-image-title-after menu-image-not-hovered">Photography</a></li>
		<li id="menu-item-944" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-944"><a href="http://www.publishing.visiomundi.net/product-category/arts/sculpture/" class="menu-image-title-after menu-image-not-hovered">Sculpture</a></li>
		<li id="menu-item-495" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-495"><a href="http://www.publishing.visiomundi.net/product-category/arts/theatre/" class="menu-image-title-after menu-image-not-hovered">Theatre</a></li>
	</ul>
</li>
</div></ul>
</li>
<li id="menu-item-678" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-678 have-submenu have-sub-menu"><a href="http://www.publishing.visiomundi.net/visiomundiopen/" class="menu-image-title-after menu-image-not-hovered">VisioMundiOpen<span class="sub-ico"> +</span></a>
<ul class="sub-menu" style="display: none;">
	<li id="menu-item-893" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-893"><a href="http://www.openmonographpress.visiomundi.net/index.php/publish" class="menu-image-title-after menu-image-not-hovered">VisioMundiOpen Monographies</a></li>
	<li id="menu-item-894" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-894"><a href="http://www.openjournals.visiomundi.net/" class="menu-image-title-after menu-image-not-hovered">VisioMundiOpen Journals</a></li>
	<li id="menu-item-1015" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1015"><a href="http://www.openconference.visiomundi.net/" class="menu-image-title-after menu-image-not-hovered">VisioMundiOpen Conference</a></li>
	<li id="menu-item-1016" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1016"><a href="http://www.openharvester.visiomundi.net/" class="menu-image-title-after menu-image-not-hovered">VisioMundiOpen Harvester</a></li>
</ul>
</li>
<li id="menu-item-172" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-172"><a href="http://www.publishing.visiomundi.net/multimedia/" class="menu-image-title-after menu-image-not-hovered">Multimedia</a></li>
<li id="menu-item-807" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-807"><a href="http://www.publishing.visiomundi.net/category/news/" class="menu-image-title-after menu-image-not-hovered">News</a></li>
<li id="menu-item-806" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-806"><a href="http://www.publishing.visiomundi.net/category/blog/" class="menu-image-title-after menu-image-not-hovered">Blog</a></li>
<li id="menu-item-135" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-135"><a href="http://www.publishing.visiomundi.net/contact/" class="menu-image-title-after menu-image-not-hovered">Contact</a></li>
</ul></div>	</nav><div class="cl"></div><!-- .site-navigation .primary-navigation -->

				</div><!-- End .container -->
			</div><!-- End .access-wrap -->